config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


 # get '/users', to: 'users#index'
 # get '/users/:id', to: 'users#show'
 get 'users/index'
 get 'chats/index'
 get 'messages/index'
 root "users#index"
 
 resources :users
 resources :chats
 resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :receiver, class_name: "User"
    has_many :messages
    validates :sender_id, presence: true
    validates :receiver_id, presence: true
    validate :diff_sender_and_receiver

    def diff_sender_and_receiver
        if sender_id == receiver_id
            errors.add(:receiver_id, "must be different from sender_id")
        end
    end
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :chat
    validates :body, presence: true
    validate :sender_must_be_in_chat

def sender_must_be_in_chat
  return unless chat && user

  unless [chat.sender_id, chat.receiver_id].include?(user_id)
    errors.add(:user_id, "must be either the sender or receiver in the chat")
  end
end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages, class_name: "Message", foreign_key: "user_id"
    has_many :received_chats, class_name: "Chat", foreign_key: "receiver_id"
    has_many :received_messages, through: :received_chats, source: :messages

    def chats
        Chat.where("sender_id = :id OR receiver_id = :id", id: self.id)
      end
    
      validates :email, presence: true, uniqueness: true
      validates :first_name, presence: true
      validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def index
        @chats = Chat.all
    end

    def show
        @chat = Chat.find(params[:id])
    end
    def new
        @chat = Chat.new
    end
    def create
        @chat = Chat.new(chat_params)
      
        if @chat.save
          redirect_to @chat, notice: 'Chat was successfully created.'
        else
          render :new, status: :unprocessable_entity
        end
    end
    def edit
        @chat = Chat.find(params[:id])
    end
    def update
        @chat = Chat.find(params[:id])
        if @chat.update(chat_params)
            redirect_to @chat, notice: 'Chat was successfully updated.'
        else
            render :edit, status: :unprocessable_entity
        end
    end
    private
    def chat_params
    params.require(:chat).permit(:sender_id, :receiver_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
        @messages = Message.all
    end

    def show
        @message = Message.find(params[:id])
    end
    def new
        @message = Message.new
    end
        
    def create
          @message = Message.new(message_params)
          if @message.save
            redirect_to @message
          else
            render :new
          end
    end

    def edit
        @message = Message.find(params[:id])
    end
    
    def update
        @message = Message.find(params[:id])
        if @message.update(message_params)
            redirect_to @message
        else
            render :edit
        end
    end
      private
      
      def message_params
        params.require(:message).permit(:chat_id, :user_id, :body)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end
    def description
        @user = User.find(params[:id])
        render json: { description: @user.description }
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user, notice: 'User was successfully created.'
        else
            render :new
        end
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to @user, notice: 'User was successfully updated.'
        else
            render :edit
        end
    end
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_form.html.erb
<%= form_with model: @chat do |form| %>
    <div class= "field">
        <%= form.label :sender_id, 'Sender' %>
        <%= form.select :sender_id, User.all.map { |u| [u.first_name, u.id]}, {}, class: 'form-select' %>
    </div>
    <div class= "field">
        <%= form.label :receiver_id, 'Receiver' %>
        <%= form.select :receiver_id, User.all.map { |u| [u.first_name, u.id]}, {}, class: 'form-select' %>
    </div>
    <div class= 'actions'>
        <%= form.submit %>
    </div>
<% end %>

app/views/chats/edit.html.erb
<h1> Edit Chat </h1>
<p> Please fill in the form below to edit the chat. </p>
<% if @chat.errors.any? %>
  <div class="alert alert-danger">
    <h4>There were some errors:</h4>
    <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: 'form' %>

<p> <%= link_to 'Back', chats_path %> </p>


app/views/chats/index.html.erb
<h1> Chats </h1>
<p> Welcome to the chats page. </p>
<table class="table"> 
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Sender</th>
      <th scope="col">Receiver</th>
      <th scope="col">Date</th>
      <th scope="col">Details</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
  <% @chats.each do |chat| %>
    <tr>
      <th scope="row"><%= chat.id %></th>
      <td><%= chat.sender_id %></td>
      <td><%= chat.receiver_id %></td>  
      <td><%= chat.created_at %></td>
      <td><%= link_to 'Show', chat_path(chat) %></td>
      <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
    </tr>
  <% end %> 
  </tbody>
</table>
<p> <%= link_to 'New Chat', new_chat_path %> </p>

app/views/chats/new.html.erb
<h1> New Chat </h1>
<p> Please fill in the form below to create a new chat. </p>
<% if @chat.errors.any? %>
  <div class="alert alert-danger">
    <h4>There were some errors:</h4>
    <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: 'form' %>
<p> <%= link_to 'Back', chats_path %> </p>

app/views/chats/show.html.erb
<h1>Chat #<%= @chat.id %> Details</h1>

<% sender = User.find(@chat.sender_id) %>
<p><strong>Sender:</strong> <%= sender.first_name %> <%= sender.last_name %> (ID: <%= sender.id %>)</p>
<% receiver = User.find(@chat.receiver_id) %>
<p><strong>Receiver:</strong> <%= receiver.first_name %> <%= receiver.last_name %> (ID: <%= receiver.id %>)</p>
<p><strong>Created At:</strong> <%= @chat.created_at.strftime("%B %d, %Y %H:%M") %></p>
<hr>
<h2>Messages</h2>
<ul>
  <% Message.where(chat_id: @chat.id).each do |message| %>
    <li>
      <strong><%= User.find(message.user_id).first_name %>:</strong>
      <%= message.body %>
    </li>
  <% end %>
</ul>
<div class='actions'>
  <%= link_to 'Edit', edit_chat_path(@chat), class: 'btn btn-secondary' %>
  <%= link_to 'Back to Chats', chats_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <%= link_to "WhatsNew", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Users", users_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Chats', chats_index_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Messages', messages_index_path, class: 'nav-link' %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Whats New" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model: @message do |form| %>
    <div class= "mb-3">
    <%= form.label :chat_id, 'Chat' %>
    <%= form.select :chat_id, Chat.all.map { |c| ["Chat##{c.id}", c.id]}, {}, class: 'form-select' %>
    </div>

    <div class= "mb-3">
    <%= form.label :user_id, 'Sender' %>
    <%= form.select :user_id, User.all.map { |u| [u.first_name, u.id] }, {}, class: "form-select" %>
  </div>

    <div class= "mb-3">
    <%= form.label :body, 'Message' %>
    <%= form.text_area :body, class: 'form-control' %>
    </div>

    <div class="actions">
        <%= form.submit class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/messages/edit.html.erb
<h1> Edit Message </h1>
<p> Please fill in the form below to edit the message. </p>
<% if @message.errors.any? %>
  <div class="alert alert-danger">
    <h4>There were some errors:</h4>
    <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: 'form' %>
<p> <%= link_to 'Back', messages_path %> </p>

app/views/messages/index.html.erb
<h1> Messages tab </h1>
<p> Welcome to the messages page. </p>

<table class="table"> 
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Chat</th>
      <th scope="col">Sender</th>
      <th scope="col">Message</th>
      <th scope="col">Date</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
  <% @messages.each do |message| %>
    <tr>
      <th scope="row"><%= message.id %></th>
      <td><%= message.chat_id %></td>
      <td><%= message.user_id %></td>
      <td><%= message.body %></td>
      <td><%= message.created_at %></td>
      <td><%= link_to 'Show', message_path(message) %></td>
      <td><%= link_to 'Edit', edit_message_path(message) %></td>
    </tr>
  <% end %> 
  </tbody>
</table>
<p> <%= link_to 'New Message', new_message_path %> </p>

app/views/messages/new.html.erb
<h1> New message </h1>
<p> Please fill in the form below to create a new message. </p>
<% if @message.errors.any? %>
  <div class="alert alert-danger">
    <h4>There were some errors:</h4>
    <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: 'form' %>
<p> <%= link_to 'Back', messages_path %> </p>

app/views/messages/show.html.erb
<h1>Message #<%= @message.id %></h1>

<p><strong>Chat ID:</strong> <%= @message.chat_id %></p>
<% sender = User.find(@message.user_id) %>
<p><strong>Sender:</strong> <%= sender.first_name %> <%= sender.last_name %> (ID: <%= sender.id %>)</p>
<p><strong>Body:</strong> <%= @message.body %></p>
<p><strong>Sent At:</strong> <%= @message.created_at.strftime("%B %d, %Y %H:%M") %></p>
#Show the associated user and chat.
<hr>
<h2>Associated User</h2>
<p><strong>User ID:</strong> <%= @message.user_id %></p>
<p><strong>First Name:</strong> <%= sender.first_name %></p>
<p><strong>Last Name:</strong> <%= sender.last_name %></p>
<p><strong>Email:</strong> <%= sender.email %></p>
<hr>
<h2>Associated Chat</h2>
<p><strong>Chat ID:</strong> <%= @message.chat_id %></p>
<p><strong>Sender ID:</strong> <%= @message.chat.sender_id %></p>
<p><strong>Receiver ID:</strong> <%= @message.chat.receiver_id %></p>
<div class='actions'>
<%= link_to 'Edit', edit_message_path(@message), class: 'btn btn-secondary' %>
<%= link_to 'Back to Messages', messages_path, class: 'btn btn-primary' %>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
    <div class="field">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, placeholder: "First Name" %>
    </div>
    
    <div class="field">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, placeholder: "Last Name" %>
    </div>

    <div class="field">
        <%= form.label :email %>
        <%= form.email_field :email, placeholder: "Email" %>
    </div>
    
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1> Edit user </h1>
<p> Please fill in the form below to edit the user. </p>
<%= render partial: 'form' %>
<p> <%= link_to 'Back', users_path %> </p>
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <h4>There were some errors:</h4>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1> Hello </h1>
<p> Welcome to the users page. </p>
<p> Here you can see the list of registered users in the system. </p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Message count</th>
      <th scope="col">Profile</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.messages.count %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <% end %>
  </tbody>
</table>

<div class="actions">
  <%= link_to 'New User', new_user_path %>
</div>
  

app/views/users/new.html.erb
<h1> New user </h1>
<p> Please fill in the form below to create a new user. </p>
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <h4>There were some errors:</h4>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render partial: 'form' %>
<p> <%= link_to 'Back', users_path %> </p>

app/views/users/show.html.erb
<h1> User #<%= @user.id %> </h1>
<p> <strong>First Name:</strong> <%= @user.first_name %> </p>
<p> <strong>Last Name:</strong> <%= @user.last_name %> </p>
<p> <strong>Email:</strong> <%= @user.email %> </p>
<hr>
<h2> Chats </h2>
<ul>
  <% @user.chats.each do |chat| %>
    <li>
      <strong>Chat ID:</strong> <%= chat.id %>
      <ul>
        <% Message.where(chat_id: chat.id, user_id: @user.id).each do |message| %>
          <li>
            <strong>Message:</strong> <%= message.body %>
            <em>(Sent at: <%= message.created_at.strftime("%B %d, %Y %H:%M") %>)</em>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>
<br>
<div class='actions'>
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-secondary' %>
    <%= link_to 'Back to Users', users_path, class: 'btn btn-primary' %>
</div>